export const dataFieldValue = {
  Properties: {
    FieldDef: [
      {
        FieldName: "Test1",
        FieldType: "TEXT",
        FieldLength: "50",
        FieldAttribute: "Primary",
        DataFieldType: "10",
        Precision: "",
        StatusFlag: "G",
      },
      {
        FieldName: "Test2",
        FieldType: "DATE",
        FieldLength: "23",
        FieldAttribute: "Unique",
        DataFieldType: "8",
        Precision: "",
        StatusFlag: "G",
      },
      {
        FieldName: "Test3",
        FieldType: "LONG",
        FieldLength: "20",
        FieldAttribute: "",
        DataFieldType: "4",
        Precision: "",
        StatusFlag: "G",
      },
    ],
    CSVInfo: {
      CSVData: {
        TableName: "Test_table",
        DatabaseType: "offLine",
        DatabaseName: "(Local)",
        CSVType: "1",
        NoOfRecords: "3",
        Header: "N",
        OrderBy: "",
        CSVFileName: "&<Test3>&&<Test3>&",
        FileExpiryTrigger: "D",
        FilePath: "&<Test3>&&<Test3>&",
        FileType: "1",
        MaskedValue: "",
        FieldSeperator: "@",
        SleepTime: "0",
        DateTimeFormat: "m/d/yyyy",
        HeaderString: "",
        FooterString: "",
      },
    },
    DataMap: [
      {
        OrderID: "1",
        FieldName: "Test2",
        MappedFieldName: "CONST_FRAUD_USER",
        FieldLength: "0",
        DocTypeId: "0",
        Quoteflag: "N",
        VariableId: "0",
        VarFieldId: "0",
        ExtMethodIndex: "-1",
        Alignment: "",
        ExportAllDocs: "",
        FwdMap: [],
        RevMap: [],
      },
      {
        OrderID: "2",
        FieldName: "Test1",
        MappedFieldName: "CONST_FRAUD_USER",
        FieldLength: "0",
        DocTypeId: "0",
        Quoteflag: "N",
        VariableId: "0",
        VarFieldId: "0",
        ExtMethodIndex: "-1",
        Alignment: "",
        ExportAllDocs: "",
        FwdMap: [],
        RevMap: [],
      },
      {
        OrderID: "3",
        FieldName: "Test3",
        MappedFieldName: "TURNOVER",
        FieldLength: "0",
        DocTypeId: "0",
        Quoteflag: "N",
        VariableId: "130",
        VarFieldId: "0",
        ExtMethodIndex: "-1",
        Alignment: "",
        ExportAllDocs: "",
        FwdMap: [],
        RevMap: [],
      },
    ],
  },
};
