const TextEditorToolbarJson = {  
    'undo': 'true' ,
    'redo': 'true' ,
    'font': 'true' , 
    'fontSize': 'true' , 
    'formatBlock': 'true' ,
    'bold': 'true' , 
    'underline': 'true' , 
    'italic': 'true' , 
    'strike': 'false' , 
    'subscript': 'false' , 
    'superscript': 'false' ,
    'paragraphStyle': 'false' ,
    'fontColor': 'true' , 
    'hiliteColor': 'true' ,
    'removeFormat': 'true' ,
    'outdent': 'true' , 
    'indent': 'true' , 
    'align': 'true' , 
    'horizontalRule': 'true' , 
    'list': 'false' , 
    'lineHeight': 'true' ,
    'table': 'false' ,
    'link': 'false' , 
    'image': 'false' , 
    'audio': 'false' , 
    'video': 'false' , 
    'math': 'false' ,
    'fullScreen': 'true' , 
    'showBlocks': 'false' , 
    'codeView': 'false' , 
    'preview': 'false' , 
    'print': 'false' , 
    'save'   : 'false',
    '1':['font'],
    '2':['bold', 'underline', 'italic', 'fontColor'],
    // '3':[],
    // '4':[],
    // '5':[],
    '6':['align', 'outdent', 'align'], 
    '7':['outdent', 'indent'],
    // '8':['table','link', 'image', 'audio', 'video', 'math'],
    // '9':['fullScreen', 'showBlocks', 'codeView', 'preview', 'print', 'save','undo', 'redo'] ,
    // '10':['undo', 'redo']             
}

export default TextEditorToolbarJson;
